# File paths
- data:
    rawFilePath: raw/
    clnFilePath: cleaned/
    outPath: output/
    outPathScratch: output-scratch/

- viz:
    xtick.labelsize: 10
    ytick.labelsize: 10
    font.size: 12
    figure.autolayout: True
    #figure.figsize: 5,3
    axes.titlesize : 14
    axes.labelsize : 10
    lines.linewidth : 1.5
    lines.markersize : 6
    legend.fontsize: 8
    font.family : Helvetica
    legend.frameon : False
    ytick.direction: "in"
    xtick.direction: "in"
    text.usetex: False
    mathtext.fontset: cm